### ISSUE TITLE
Ensure Zendesk targets and triggers are reconciled with their desired state

### ISSUE THREAD

**Issue by JeffNeff** [triggermesh/knative-sources#39]
Currently if you were to deploy a source and mark the 'Trigger' Inactive in the Zendesk UI. If you re-deploy with the same settings the 'Trigger' will not be updated or re-created. 

~~If you deploy under one namespace and then re-deploy with the same settings in another namespace the old 'Trigger' and 'Extension' will register as valid and a new one will not be created.~~

**Comment by JeffNaef-Triggermesh** [comment]
"If you deploy under one namespace and then re-deploy with the same settings in another namespace the old 'Trigger' and 'Extension' will register as valid and a new one will not be created." this part has ben resolved by the above PR.

**Comment by JeffNaef-Triggermesh** [comment]
should have been a separate issue to begin with. my fault.

**Comment by antoineco** [comment]
@JeffNaef-Triggermesh I don't think we should let users deactivate triggers manually. The controller is there to ensure the trigger is always active, otherwise the source is effectively unusable although it reports status "OK".

If a user want to disable a trigger, they should simply delete the instance of the ZendeskSource, which in turn will (I hope?) delete the trigger and target it created.

**Comment by JeffNaef-Triggermesh** [comment]
@antoineco when you say " let users deactivate triggers" You mean "we dont support this" right? Because we have no way of preventing them from deleting it (to my knowledge)

**Comment by antoineco** [comment]
Right, but we _do_ have a way to recreate the trigger if it's been deleted, and to undo the changes performed users (remember that reconciliation logic I showed you for Azure Activity Logs?).

When this is implemented, we should add a warning to the docs saying manual changes will be reverted, the trigger and target are under the supervision of the source only.
